### ISSUE TITLE
Cant change color stuck on pink

### ISSUE THREAD

**Issue by lllllIIIIIllll** [Nepeta/MitsuhaXI#44]
I already installed audiosnapshotserver and nothing changes the color help

**Comment by williammetcalf-lilly** [comment]
If you aren't doing dynamic colors, it seems like you need to restart your device (yes, a full restart, meaning you need to rerun electra...) for static color to apply

**Comment by williammetcalf** [comment]
It seems like you need to actually do a full device restart to make the chosen color apply (yes, a full restart/rerun electra)

**Comment by Ominousness** [comment]
It will be fixed soon.

**Comment by Nepeta** [comment]
Fixed.
